

 export const questions = [
    {
        id: 0,
        qnumber: '1',
        question: 'Does the ICT have closed functionality?',
        requirements: [
            '5.1.2.1 Closed functionality', 
            '5.1.2.2 Assistive technology', 
            '5.1.4 Functionality closed to text enlargement', 
            '5.1.5 Visual output for auditory information',
            ],
        nextTrue: 1,
        nextFalse: 5,
    },
    {
        id: 1,
        qnumber: '1.1',
        question: 'Is visual information needed to enable the use of those functions of ICT that are closed to assistive technologies for screen reading?',
        requirements: [
            '5.1.3.1 General (non-visual access)', 
            '5.1.3.16 Receipts, tickets and transactional outputs',
        ],
        nextTrue: 2,
        nextFalse: 4,
    },
    {
        id: 2,
        qnumber: '1.1.1',
        question: 'Is auditory output provided as non-visual access to closed functionality?',
        requirements: [
            '5.1.3.2 Auditory oputput delivery including speech', 
            '5.1.3.3 Auditory output correlation',
            '5.1.3.8 Masked entry',
            '5.1.3.9 Private access to personal data',
            '5.1.3.10 Non-interfering audio output',
            '5.1.3.11 Private listening volume',
            '5.1.3.12 Speaker volume',
            '5.1.3.13 Volume reset',
        ],
        nextTrue: 3,
        nextFalse: 4,
    },
    {
        id: 3,
        qnumber: '1.1.1.1',
        question: 'Is speech output provided as non-visual access to closed functionality?',
        requirements: [
            '5.1.3.4 Speech output user control', 
            '5.1.3.5 Speech output automatic interruption',
            '5.1.3.6 Speech output for non-text content',
            '5.1.3.7 Speech output for video information',
            '5.1.3.14 Spoken languages',
            '5.1.3.15 Non-visual error identification',
        ],
        nextTrue: 4,
        nextFalse: 4,
    },
    {
        id: 4,
        qnumber: '1.2',
        question: 'Is ICT functionality closed to keyboards or keyboard interfaces?',
        requirements: [
            '5.1.6.1 Closed functionality (operation without keyboard interface)', 
            '5.1.6.2 Input focus (operation without keyboard interface)',
        ],
        nextTrue: 5,
        nextFalse: 5,
    },
    {
        id: 5,
        qnumber: '2',
        question: 'Does the ICT have operable parts?',
        requirements: [
            '5.5.1 Means of operation', 
            '5.5.2 Operable parts discernibility',
        ],
        nextTrue: 6,
        nextFalse: 6,
    },
    {
        id: 6,
        qnumber: '3',
        question: 'Does the ICT have a locking or toggle control?',
        requirements: [
            '5.6.1 Tactile or auditory status (locking or toggle controls)', 
            '5.6.2 Visual status (locking or toggle controls)',
        ],
        nextTrue: 7,
        nextFalse: 7,
    },
    {
        id: 7,
        qnumber: '4',
        question: 'Does the ICT provide two-way voice communication?',
        requirements: [
            '6.1 Audio bandwidth for speech', 
            '6.2.1.1 RTT Provision',
            '6.2.1.2 Concurrent voice and text',
            '6.3 Caller ID',
            '6.4 Alternatives to voice-based services',
            '13.2 Access to relay services',
            '13.3 Access to emergency services',
        ],
        nextTrue: 8,
        nextFalse: 11,
    },
    {
        id: 8,
        qnumber: '4.1',
        question: 'Does the ICT have RTT capabilities?',
        requirements: [
            '6.2.2.1 Visually distinguishable display', 
            '6.2.3 Interoperability',
            '6.2.4 Real-time text responsiveness',
        ],
        nextTrue: 9,
        nextFalse: 10,
    },
    {
        id: 9,
        qnumber: '4.1.1',
        question: 'Does the ICT support assistive technologies (i.e. it is not closed)?',
        requirements: [
            '6.2.2.2 Programmatically determinable send and receive direction', 
        ],
        nextTrue: 10,
        nextFalse: 10,
    },
    {
        id: 10,
        qnumber: '4.2',
        question: 'Does the ICT include real-time video functionality?',
        requirements: [
            '6.5.2 Resolution', 
            '6.5.3 Frame rate',
            '6.5.4 Synchronization between audio and video',
            '6.6 Alternatives to video-based services',
        ],
        nextTrue: 11,
        nextFalse: 11,
    },
    {
        id: 11,
        qnumber: '5',
        question: 'Does the ICT have video capabilities (playing, transmitting, converting or recording)?',
        requirements: [
            '7.1.1 Captioning playback', 
            '7.1.2 Captioning synchronization',
            '7.1.3 Preservation of captioning',
            '7.2.1 Audio description playback',
            '7.2.2 Audio description synchronization',
            '7.2.3 Preservation of audio description',
            '7.3 User controls for captions and audio description',
        ],
        nextTrue: 12,
        nextFalse: 12,
    },
    {
        id: 12,
        qnumber: '6',
        question: 'Is the ICT hardware or does the ICT has hardware?',
        requirements: [
            '8.1.2 Standard connections', 
            '8.1.3 Colour',
            '8.3.5 Installation instructions',
            '8.4.3 Keys, tickets and fare cards',
            '8.5 Tactile indication of speech mode',
        ],
        nextTrue: 13,
        nextFalse: 16,
    },
    {
        id: 13,
        qnumber: '6.1',
        question: 'Has the ICT hardware speech output?',
        requirements: [
            '8.2.1.1 Speech volume range',
            '8.2.1.2 Incremental volume control',
            '8.2.2.1 Fixed-line devices',
            '8.2.2.2 Wireless communication devices',
        ],
        nextTrue: 14,
        nextFalse: 14,
    },
    {
        id: 14,
        qnumber: '6.2',
        question: 'Does the ICT have physical dimensions that are integral to the ICT and that may restrict physical access?',
        requirements: [
            '8.3.2.1 Change in level?',
            '8.3.2.2 Clear floor or ground space',
            '8.3.2.3.1 General (approach)',
            '8.3.2.3.2 Forward approach',
            '8.3.2.3.3 Parallel approach',
            '8.3.2.4 Knee and toe clearance width',
            '8.3.2.5 Toe clearance',
            '8.3.2.6 Knee clearance',
            '8.3.3.1.1 Unobstructed high forward reach',
            '8.3.3.1.2 Unobstructed low forward reach',
            '8.3.3.1.3.1 Clear floor space (obstructed reach)',
            '8.3.3.1.3.2 Obstructed (<510 mm) forward reach  8.3.3.1.3.3 Obstructed (< 635 mm) forward reach  8.3.3.2.1 Unobstructed high side reach',
            '8.3.3.2.2 Unobstructed low side reach',
            '8.3.3.2.3.1 Obstructed (<= 255 mm) side reach',
            '8.3.3.2.3.2 Obstructed (<= 610 mm) side reach',
            '8.3.4 Visibility',
        ],
        nextTrue: 15,
        nextFalse: 15,
    },
    {
        id: 15,
        qnumber: '6.3',
        question: 'Does the ICT have mechanically operable parts?',
        requirements: [
            '8.4.1 Numeric keys',
            '8.4.2.1 Means of operation of mechanical parts',
            '8.4.2.2 Force of operation of mechanical parts',
        ],
        nextTrue: 16,
        nextFalse: 16,
    },
    {
        id: 16,
        qnumber: '7',
        question: 'Is the ICT a web page or does the ICT have web pages?',
        requirements: [
            '9.2.1 Non-text content',
            '9.2.2 Audio-only and video-only (pre-recorded)',
            '9.2.3 Captions (pre-recorded)',
            '9.2.4 Audio description or media alternative (pre-recorded) o 9.2.5 Captions (live)',
            '9.2.6 Audio description (pre-recorded)',
            '9.2.7 Info and relationships',
            '9.2.8 Info and relationships',
            '9.2.9 Sensory characteristics o 9.2.10 Use of colour',
            '9.2.11 Audio control',
            '9.2.12 Contrast (minimum) o 9.2.13 Resize text',
            '9.2.14 Images of text',
            '9.2.15 Keyboard',
            '9.2.16 No keyboard trap',
            '9.2.17 Timing adjustable',
            '9.2.18 Pause, stop, hide',
            '9.2.19 Three flashes or below threshold',
            '9.2.20 Bypass blocks',
            '9.2.21 Page titled',
            '9.2.22 Focus order',
            '9.2.23 Link purpose',
            '9.2.24 Multiple ways',
            '9.2.25 Headings and labels',
            '9.2.26 Focus visible',
            '9.2.27 Language of page',
            '9.2.28 Language of parts',
            '9.2.29 On focus',
            '9.2.30 On input',
            '9.2.31 Consistent navigation',
            '9.2.32 Consistent identification',
            '9.2.33 Error identification',
            '9.2.34 Labels or instructions',
            '9.2.35 Error suggestion',
            '9.2.36 Error prevention (legal, financial, data) o 9.2.37 Parsing',
            '9.2.38 Name, role, value',
            '9.3 WCAG 2.0 conformance requirements',
        ],
        nextTrue: 17,
        nextFalse: 17,
    },
    {
        id: 17,
        qnumber: '8',
        question: 'Is the ICT a non-web document or does the ICT have non-web documents?',
        requirements: [
            '10.2.1 Non-text content',
            '10.2.2 Audio-only and video-only (pre-recorded)',
            '10.2.3 Captions',
            '10.2.4 Audio description or media alternative (pre-recorded) o 10.2.5 Captions (live)',
            '10.2.6 Audio description (pre-recorded)',
            '10.2.7 Info and relationships',
            '10.2.8 Meaningful sequence',
            '10.2.9 Sensory characteristics',
            '10.2.10 Use of colour',
            '10.2.11 Audio control',
            '10.2.12 Contrast (minimum)',
            '10.2.13 Resize text',
            '10.2.14 Images of text',
            '10.2.15 Keyboard',
            '10.2.16 No keyboard trap',
            '10.2.17 Timing adjustable',
            '10.2.18 Pause, stop, hide',
            '10.2.19 Three flashes or below threshold',
            '10.2.21 Document titled',
            '10.2.22 Focus order',
            '10.2.23 Link purpose (in context)',
            '10.2.25 Headings and labels',
            '10.2.26 Focus visible',
            '10.2.27 Language of page',
            '10.2.28 Language of parts',
            '10.2.29 On focus',
            '10.2.30 On input',
            '10.2.33 Error identification',
            '10.2.34 Labels or instructions',
            '10.2.35 Error suggestion',
            '10.2.36 Error prevention (legal, financial, data) o 10.2.37 Parsing',
            '10.2.38 Name, role, value',
            '10.2.39 Caption positioning',
            '10.2.40 Audio description timing',
        ],
        nextTrue: 18,
        nextFalse: 18,
    },
    {
        id: 18,
        qnumber: '9',
        question: 'Is the ICT software or does the ICT have software?',
        requirements: [
            '11.4.2 No disruption of accessibility features',
            '11.3.2.04 Assistive technologies',
            '11.5 User preferences',
        ],
        nextTrue: 19,
        nextFalse: 26,
    },
    {
        id: 19,
        qnumber: '9.1',
        question: 'Is it non-web software that provides a user interface?',
        requirements: [
            '11.2.1.03 Captions (pre-recorded)',
            '11.2.1.05 Captions (live)',
            '11.2.1.06 Audio description (pre-recorded)',
            '11.2.1.09 Sensory characteristics  11.2.1.10 Use of colour',
            '11.2.1.11 Audio control',
            '11.2.1.12 Contrast (minimum)',
            '11.2.1.17 Timing adjustable',
            '11.2.1.18 Pause, stop, hide',
            '11.2.1.19 Three flashes or below threshold',
            '11.2.1.22 Focus order',
            '11.2.1.23 Link purpose (in context)',
            '11.2.1.25 Headings and labels',
            '11.2.1.26 Focus visible',
            '11.2.1.29 On focus',
            '11.2.1.30 On input',
            '11.2.1.34 Labels or instruction',
            '11.2.1.35 Error suggestion',
            '11.2.1.36 Error prevention (legal, financial, data)',
        ],
        nextTrue: 20,
        nextFalse: 22,
    },
    {
        id: 20,
        qnumber: '9.1.1',
        question: 'Does the non-web software have functionality that supports access to assistive technologies (i.e. it is not closed)?',
        requirements: [
            '11.2.1.1 Non-text content (screen reading supported)',
            '11.2.1.2 Audio-only and video-only (pre-recorded)',
            '11.2.1.4 Audio description or media alternative (pre-recorded)',
            '11.2.1.7 Info and relationships',
            '11.2.1.8 Meaningful sequence',
            '11.2.1.13 Resize text',
            '11.2.1.14 Images of text',
            '11.2.1.15 Keyboard',
            '11.2.1.16 No keyboard trap',
            '11.2.1.27 Language of software',
            '11.2.1.33 Error identification',
            '11.2.1.37 Parsing',
            '11.2.1.38 Name, role, value',
        ],
        nextTrue: 21,
        nextFalse: 21,
    },
    {
        id: 21,
        qnumber: '9.1.2',
        question: 'Doesthenon-websoftwarehaveclosedfunctionality?',
        requirements: [
            '11.2.2.1 Non-text content',
            '11.2.2.2.1 Pre-recorded audio-only',
            '11.2.2.2.2 Pre-recorded video only',
            '11.2.2.4 Audio description or media alternative (pre-recorded)',
            '11.2.2.7 Info and relationships',
            '11.2.2.8 Meaningful sequence',
            '11.2.2.13 Resize text',
            '11.2.2.14 Images of text',
            '11.2.2.15 Keyboard',
            '11.2.2.27 Language of software',
            '11.2.2.33 Error Identification',
            '11.2.2.37 Parsing',
            '11.2.2.38 Name, role value',
        ],
        nextTrue: 22,
        nextFalse: 22,
    },
    {
        id: 22,
        qnumber: '9.2',
        question: 'Is it platform software?',
        requirements: [
            '11.3.2.1 Platform accessibility service support for software that provides a user interface',
            '11.3.2.2 Platform accessibility service support for assistive technologies',
            '11.4.1 User control of accessibility features',
        ],
        nextTrue: 23,
        nextFalse: 23,
    },
    {
        id: 23,
        qnumber: '9.3',
        question: 'Does the software supports access to assistive technologies (i.e. it is not closed)?',
        requirements: [
            '11.3.2.03 Use of accessibility services  11.3.2.05 Object information',
            '11.3.2.06 Row, column, and headers  11.3.2.07 Values',
            '11.3.2.08 Label relationships',
            '11.3.2.09 Parent-child relationships  11.3.2.10 Text',
            '11.3.2.11 List of available actions',
            '11.3.2.12 Execution of available actions',
            '11.3.2.13 Tracking of focus and selection attributes',
            '11.3.2.14 Modification of focus and selection attributes  11.3.2.15 Change notification',
            '11.3.2.16 Modifications of states and properties',
            '11.3.2.17 Modifications of values and text',
        ],
        nextTrue: 24,
        nextFalse: 24,
    },
    {
        id: 24,
        qnumber: '9.4',
        question: 'Does the non-web software have closed functionality?',
        requirements: [
            '11.3.1 Closed functionality (interoperability with assistive technology)',
        ],
        nextTrue: 25,
        nextFalse: 25,
    },
    {
        id: 25,
        qnumber: '9.5',
        question: 'Is the ICT an authoring tool?',
        requirements: [
            '11.6.1 Content technology',
            '11.6.2 Accessible content creation',
            '11.6.3 Preservation of accessibility information in transformations  11.6.4 Repair assistance',
            '11.6.5 Templates',
        ],
        nextTrue: 26,
        nextFalse: 26,
    },
    {
        id: 26,
        qnumber: '10',
        question: 'Does the ICT have product documentation?',
        requirements: [
            '12.1.1 Accessibility and compatibility features',
            '12.1.2 Accessible documentation',
        ],
        nextTrue: 27,
        nextFalse: 27,
    },
    {
        id: 27,
        qnumber: '11',
        question: 'Does the ICT have support services?',
        requirements: [
            '12.2.2 Information on accessibility and compatibility services ',
            '12.2.3 Effective communication',
            '12.2.4 Accessible documentation',
        ],
        nextTrue: 28,
        nextFalse: 28,
    },
    {
        id: 29,
        qnumber: '12',
        question: 'Is the ICT intended to provide relay services?',
        requirements: [
            '13.1.2 Text relay services',
            '13.1.3 Sign relay services',
            '13.1.4 Lip-reading relay services',
            '13.1.5 Captioned telephony services ',
            '13.1.6 Speech to speech relay services',
        ],
        nextTrue: null,
        nextFalse: null,
    },

];